// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMxn3QMFxorkAG7_sXQYtO8UlhMzsHlTI',
    appId: '1:594972828394:web:226331a0774b54c5a5ed93',
    messagingSenderId: '594972828394',
    projectId: 'round-gamma-421917',
    authDomain: 'round-gamma-421917.firebaseapp.com',
    storageBucket: 'round-gamma-421917.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5-NQZr_Duf7FjFVL70jtdamRMSA03Amo',
    appId: '1:594972828394:android:26dc7d860a02b10aa5ed93',
    messagingSenderId: '594972828394',
    projectId: 'round-gamma-421917',
    storageBucket: 'round-gamma-421917.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYXwoZsQBlPgztycQl2_y6SQaiaoIphi0',
    appId: '1:594972828394:ios:fef7ed03d567365da5ed93',
    messagingSenderId: '594972828394',
    projectId: 'round-gamma-421917',
    storageBucket: 'round-gamma-421917.appspot.com',
    iosBundleId: 'com.example.eLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYXwoZsQBlPgztycQl2_y6SQaiaoIphi0',
    appId: '1:594972828394:ios:fef7ed03d567365da5ed93',
    messagingSenderId: '594972828394',
    projectId: 'round-gamma-421917',
    storageBucket: 'round-gamma-421917.appspot.com',
    iosBundleId: 'com.example.eLibrary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMxn3QMFxorkAG7_sXQYtO8UlhMzsHlTI',
    appId: '1:594972828394:web:0f75005a9538b988a5ed93',
    messagingSenderId: '594972828394',
    projectId: 'round-gamma-421917',
    authDomain: 'round-gamma-421917.firebaseapp.com',
    storageBucket: 'round-gamma-421917.appspot.com',
  );
}
